Typefully Revamp
typefully/minimal-twitter pull request #126
Opened 2022-11-10 15:47 UTC by linuz90

We've just acquired **Minimal Twitter** from @thomaswang 💫 

Since it's now part of the [Typefully](https://typefully.com) brand, this PR changes old references to Thomas's websites to new pages hosted on `typefully.com`. 

It adds a new "welcome screen" that is shown to users when they install or update the extension.

Finally, it makes small tweaks to the extension UI.

2022-11-11 07:56 UTC, thomaswang approved these changes
+ made small changes to README (centering logo, adding h1, moving description further down).

2022-11-11 10:01 UTC, thomaswang requested changes
@linuz can you add this to `main.css`?

This will fix the misalignment issue at smaller screen sizes of the nav.

```css
/* Only display generated list button at large screen */
@media only screen and (min-width: 1264px) {
  #mt-listsButtonNode {
    display: none;
  }
}
```

Alternatively, can do this:
```css
/* Only display generated list button at large screen */
@media only screen and (min-width: 1264px) {
  #mt-listsButtonNode > div > div:last-child {
    display: none;
  }
}
```

2022-11-11 10:23 UTC, thomaswang approved these changes

2022-11-12 09:51 UTC, frankdilo approved these changes

2022-11-12 09:55 UTC, merged